module.exports = {
	BAD_PARAMETERS: 400,
	ARTICLE_NOT_FOUND: 400,
	JOURNAL_NOT_FOUND: 400,
	ROLE_ALREADY_CREATED: 400,
	ARTICLE_BAD_STATUS: 403,
	AUTHOR_NOT_LEAD: 403,
	INVITATION_REVIEW_FORBIDEN_OPERATION: 403,
	ARTICLE_FORBIDEN_OPERATION: 403,
	JOURNAL_FORBIDEN_OPERATION: 403,
	JOURNAL_FORBIDEN_INVITATION: 403,
	NO_PREPRINT_COLLECTION: 500
};
